#!/usr/bin/env python3
"""Generate main/crypto_vectors.h from the reference implementation (aioairctrl).

The firmware's self-test checks philips_crypto.c against these, so the C port is proven
against the Python code that Home Assistant users run, not against itself.

    python3 -m venv /tmp/v && /tmp/v/bin/pip install aioairctrl==0.3.1
    /tmp/v/bin/python tools/crypto_vectors.py > main/crypto_vectors.h
"""
import json
import pathlib

from aioairctrl.coap.encryption import EncryptionContext

HERE = pathlib.Path(__file__).resolve().parent


def enc(counter_before: str, plaintext: str) -> str:
    ctx = EncryptionContext()
    ctx.set_client_key(counter_before)
    return ctx.encrypt(plaintext)


def c_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    control = json.dumps({"state": {"desired": {"CommandType": "app", "DeviceId": "",
                                                 "EnduserId": "", "D03102": 1}}})
    status = json.dumps(json.loads((HERE.parent / "test/ac2220_status.json").read_text()),
                        separators=(",", ":"))
    vectors = [
        # name, counter before encrypt, plaintext
        ("control", "00000000", control),        # counter increments to 00000001
        ("wrap", "FFFFFFFF", "{}"),              # counter wraps to 00000000
        ("status", "5BD4D2C5", status),          # full AC2220 status, realistic size
    ]
    print("// Generated by tools/crypto_vectors.py from aioairctrl 0.3.1. Do not edit.")
    print("#pragma once\n")
    print("typedef struct { const char *name, *counter_before, *plaintext, *encrypted; } crypto_vector_t;\n")
    print("static const crypto_vector_t CRYPTO_VECTORS[] = {")
    for name, ctr, pt in vectors:
        ct = enc(ctr, pt)
        assert EncryptionContext().decrypt(ct) == pt
        print(f"    {{{c_str(name)}, {c_str(ctr)},\n     {c_str(pt)},\n     {c_str(ct)}}},")
    print("};")


if __name__ == "__main__":
    main()
